# -*- coding: utf-8 -*-
"""StableDiffusion_ImageGen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gUI9R72N-h8XUT-Fq8blcYuPeJCr1jNy
"""

!pip install -q diffusers transformers accelerate

from diffusers import StableDiffusionPipeline
import torch

# 🔐 Enter your HuggingFace token below
YOUR_TOKEN = "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"  # Replace this!

pipe = StableDiffusionPipeline.from_pretrained(
    "CompVis/stable-diffusion-v1-4",
    use_auth_token=YOUR_TOKEN,
    torch_dtype=torch.float16,
    revision="fp16"
)

pipe = pipe.to("cuda")

prompt = "A serene futuristic cityscape at golden hour, with sleek glass towers, flying cars gliding through the sky, and lush rooftop gardens glowing under the soft sunlight. Ultra-realistic, cinematic lighting, 8K resolution."

image = pipe(prompt).images[0]

# Create the folder first
!mkdir -p generated_images

# Save and view the image
image.save("generated_images/futuristic_cityscape.png")
image.show()

image.show()

prompt = "An ancient temple floating in the clouds, surrounded by glowing birds and waterfalls, painted in cinematic light."

image = pipe(prompt).images[0]
!mkdir -p generated_images
image.save("generated_images/temple_in_clouds.png")
image.show()

prompt = "A monk meditating in a floating glass sphere above a digital ocean, with binary code rain and calm futuristic background"
image = pipe(prompt).images[0]
!mkdir -p generated_images
image.save("generated_images/monk_floating_sphere.png")
image.show()

prompt = "An ultra-modern minimalistic workspace with sleek furniture, ambient lighting, and a panoramic city skyline view at dusk, rendered in photorealistic 8K quality"
image = pipe(prompt).images[0]
!mkdir -p generated_images
image.save("generated_images/futuristic_minimalism.png")
image.show()

prompt = "A glowing AI core chamber in a futuristic lab, blue and violet lighting, spinning data orbs, robotic arms maintaining the system, sci-fi detail, cinematic shadows, digital haze, ultra-resolution"
image = pipe(prompt).images[0]
image.save("generated_images/ai_core_room.png")
image.show()

# Prompt
prompt = "A hyper-realistic digital brain made of glowing circuits and neural links, suspended in a dark void, surrounded by holographic data streams, sci-fi ambiance, high-tech interface, cinematic lighting"

# Generate Image
image = pipe(prompt).images[0]

# Save and Display
image.save("generated_images/digital_brain_hd.png")
image.show()

# Heaven-themed prompt
prompt = "A breathtaking heavenly landscape with glowing clouds, golden light rays breaking through the sky, floating crystal islands, angelic architecture with marble arches and waterfalls cascading into the stars, soft ethereal lighting, ultra-HD cinematic fantasy"

# Generate image
image = pipe(prompt).images[0]

# Ensure folder exists
import os
os.makedirs("generated_images", exist_ok=True)

# Save and show image
image.save("generated_images/celestial_sanctuary.png")
image.show()

# Realistic Indian City Prompt
prompt = "A realistic Indian cityscape during the golden hour, showing crowded streets with auto-rickshaws, people walking in traditional and modern clothing, colorful buildings, street vendors selling snacks, temples in the background, overhead electric wires, dust in the air, realistic lighting and architecture, 4K detail, busy urban atmosphere"

# Generate image
image = pipe(prompt).images[0]

# Save the image
import os
os.makedirs("generated_images", exist_ok=True)
image.save("generated_images/realistic_indian_city.png")

# Show the image
image.show()